# Generated by Django 4.2.6 on 2024-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
