# Generated by Django 4.2.6 on 2024-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechCraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='audio')),
            ],
        ),
    ]
