# Generated by Django 4.2.6 on 2024-03-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechCraft', '0002_saveaudio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveAudio',
        ),
    ]
